### ISSUE TITLE
Use libvips

### ISSUE THREAD

**Issue by barmintor** [cul/imogen#1]
These benchmarks are compelling, especially since we are primarily tiling and rotating (simple operations): http://www.vips.ecs.soton.ac.uk/index.php?title=Speed_and_Memory_Use

I'd want to get some buy in from @litosysadmin since the machine images are their responsibility. We'd still need OpenCV and ImageMagick for jp2, but the derivatives may be fast enough to allow for a managed cache downstream.

**Comment by ttp2113** [comment]
I'd like to look into this a bit more but a cursory glance indicates that vips would not require any more effort than what we currently put into managing deployments of existing image processing libraries. If it could promote the adoption of a managed cache, then I'm definitely in support of it. Let me know if you want to give it a spin on a test host.

**Comment by elohanlon** [comment]
Closing this issue because imogen uses libvips now!
